apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/homework/index.html"]
      volumeMounts:
        - name: front-static
          mountPath: "/homework"
        - name: nginx-conf
          mountPath: "/etc/nginx/conf.d/"
  initContainers:
    - name: download-static
      image: busybox:1.28
      command: 
        - wget
        - "-O"
        - "/init/index.html"
        - "http://info.cern.ch"
      volumeMounts:
        - name: front-static
          mountPath: "/init"
  volumes:
    - name: front-static
      emptyDir: {}  
    - name: nginx-conf 
      configMap:
        name: nginx-conf
        items:
        - key: default.conf
          path: default.conf